### ISSUE TITLE
Cannot start application

### ISSUE THREAD

**Issue by DarrenMa** [pauleve/docker-mtgo#152]
Hi, first time trying dockerized mtgo and I think it's an awesome idea.

When I try run `./run-mtgo` I land up with an error "Cannot start application"
The terminal looks like this:

```
./run-mtgo
IMAGE=panard/mtgo:latest
run(): docker run --privileged --rm -e DISPLAY -v mtgo-data-dma:/home/wine/.wine/host/ -v mtgo-data-dma:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/dma/.local/share/mtgo/Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/Europe/Rome --name mtgo_running panard/mtgo:latest mtgo
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
winetricks gdiplus=native sound=alsa winegstreamer=disabled wmp=disabled
Executing mkdir -p /home/wine
Using winetricks 20220411-next - sha256sum: d23dbdf84a2f75b0cbb9608f9ba9d65ee23947fdf71be76115c9eb066b3b3100 with wine-7.7 and WINEARCH=win32
Using native override for following DLLs: gdiplus
Executing wine regedit C:\windows\Temp\_native\override-dll.reg
Executing w_do_call sound=alsa
Executing mkdir -p /home/wine
Executing load_sound alsa
Setting sound driver to alsa
Executing wine regedit C:\windows\Temp\set-sound.reg
Using  override for following DLLs: winegstreamer
Executing wine regedit C:\windows\Temp\_disabled\override-dll.reg
Using  override for following DLLs: wmp
Executing wine regedit C:\windows\Temp\_disabled\override-dll.reg
wineboot
wine /opt/mtgo/mtgo.exe
01e0:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
01e0:err:ole:com_get_class_object no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
01e0:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
01e0:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
01e0:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
01e0:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
01e0:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
01e0:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
01e0:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
01e0:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
wine: Call from 7B012116 to unimplemented function ncrypt.dll.NCryptExportKey, aborting
```

And here's the error generated straight after it downloads MTGO

```
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3062.0 built by: NET472REL1
	clr.dll 			: 4.7.3062.0 built by: NET472REL1
	dfdll.dll 			: 4.7.3062.0 built by: NET472REL1
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application
						Server		: AkamaiNetStorage
	Application url			: http://mtgoclientdepot.onlinegaming.wizards.com/3.4.126.4187.20220427104736/MTGO.exe.manifest
						Server		: AkamaiNetStorage

IDENTITIES
	Deployment Identity		: MTGO.application, Version=3.4.126.4187, Culture=neutral, PublicKeyToken=92a8f782d852ef89, processorArchitecture=msil
	Application Identity		: MTGO.exe, Version=3.4.126.4187, Culture=neutral, PublicKeyToken=92a8f782d852ef89, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application resulted in exception. Following failure messages were detected:
		+ File, EmblemDefaultArt.jpg, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [4/30/2022 9:38:21 PM] : Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application has started.
	* [4/30/2022 9:38:21 PM] : Processing of deployment manifest has successfully completed.
	* [4/30/2022 9:38:21 PM] : Installation of the application has started.
	* [4/30/2022 9:38:22 PM] : Processing of application manifest has successfully completed.
	* [4/30/2022 9:38:26 PM] : Found compatible runtime version 4.0.30319.
	* [4/30/2022 9:38:26 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [4/30/2022 9:41:43 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, EmblemDefaultArt.jpg, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.FileComponent.Verify()
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

Machine details:
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

**Comment by pauleve** [comment]
You can give a try to `./run-mtgo --reset`, and if it still persists, run the following command
```
./run-mtgo --debug &>mtgo.log
```
and attach the mtgo.log file to this issue.

**Comment by DarrenMa** [comment]
I tried `./run-mtgo --reset` and got the same result.

Ran `./run-mtgo --debug &>mtgo.log` and attached the log file.
[mtgo.log](https://github.com/pauleve/docker-mtgo/files/8597739/mtgo.log)

**Comment by pauleve** [comment]
From various posts on reddit, e.g., https://www.reddit.com/r/MTGO/comments/6d9o64/cant_play_mtgo_anymore/, if the reset does not work, you may try using another internet service provider (through smartphone for instance)

**Comment by DarrenMa** [comment]
As you suggested, changed wifi and it worked!
