### ISSUE TITLE
Application Tried to create a window but no driver could be loaded

### ISSUE THREAD

**Issue by AAfghahi** [pauleve/docker-mtgo#169]
<insert issue description here>

Hello, I've been trying to get mtgo to work on this and running into no luck! I tried installing an X server and enabled X11forwarding, but I do not think that those are what is causing this error. I've noticed that others have had this issue, but they were on macs. 

OS: Linux
  Operating System: Linux Mint 20.2
            Kernel: Linux 5.4.0-74-generic
      Architecture: x86-64

Desktop environment (for Linux): <Gnome, KDE, ...>
Graphics card: MSI Radeon RX 580 8GB
Output of `docker info`:
```
Unhandled Exception: System.ComponentModel.Win32Exception: Error creating window handle.
at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
at System.Windows.Forms.Control.CreateHandle()
at System.Windows.Forms.Form.CreateHandle()
at System.Windows.Forms.Control.get_Handle()
at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
at System.Deployment.Application.UserInterfaceForm.SetVisibleCore(Boolean value)
at System.Windows.Forms.Control.set_Visible(Boolean value)
at System.Deployment.Application.SplashPiece.ShowSplash(Form parentForm)
at System.Deployment.Application.SplashPiece..ctor(UserInterfaceForm parentForm, SplashInfo info)
at System.Deployment.Application.UserInterfaceForm.InitializeContent()
at System.Deployment.Application.UserInterfaceForm..ctor(ManualResetEvent readyEvent, SplashInfo splashInfo)
at System.Deployment.Application.UserInterface.UIThread()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 158 at address 7B012446 (thread 0158), starting debugger...
0174:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0174:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
016c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
016c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."

```

<attach `output.log` file from `./run-mtgo &>output.log`>

**Comment by HeebaSteve** [comment]
I am having this same issue on my Mac.

**Comment by Zharend** [comment]
I'm also having the same issue on my Linux system. I am using X11.

OS: Pop!_OS 22.04 LTS x86_64
Kernel: 6.4.6-76060406-generic

**Comment by engineerNg** [comment]
same

**Comment by pauleve** [comment]
There is probably an issue with security settings on the distribution.
Can you try:
```
./run-mtgo --  --security-opt seccomp=unconfined panard/mtgo:latest
```
or
```
./run-mtgo --  --security-opt label:disable panard/mtgo:latest
```
?

**Comment by HighlyTrainedNeuralNetwork** [comment]
I'm running into what seems like the same issue on Ubuntu 22.04.4 LTS, Linux 6.5.0-27-generic, x86-64. Output when I try running the commands suggested in your last message seems unchanged. I'm attaching the output from just ./run-mtgo.
[output.txt](https://github.com/pauleve/docker-mtgo/files/14976700/output.txt)

**Comment by bungjared** [comment]
Same problem, Debian 12, LXQt 1.2.0 Linux 6.1.0-20-amd64.

**Comment by qemqemqem** [comment]
> `./run-mtgo -- --security-opt label:disable panard/mtgo:latest`

I'm having the same trouble. @pauleve I ran both commands that you suggested and I see no change. I get the same output as @HighlyTrainedNeuralNetwork.

**Comment by pauleve** [comment]
Maybe doing `xhost +` before the `run-mtgo` command might help.
Otherwise, is your UID different from 1000? (`echo $UID`)

**Comment by jcastonguay** [comment]
Ran into a similar issue. Running `xhost +local:1000` worked which was odd. Thinking that the container couldn't read the Xauth files, I added `--security-opt label=type:container_runtime_t ` to the ${opts} for docker run and that worked.
