### ISSUE TITLE
MTGO fails to download when launched after --reset --update

### ISSUE THREAD

**Issue by chumpblocckami** [pauleve/docker-mtgo#180]
Hi,
I used the mtgo-docker without any problem until an unfortunate 
`./run-mtgo --reset --update`
that took place because i thought it will fix some minor glitch, but after running the aforementioned script i wasn't be able to re-install the game.

OS: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Desktop environment (for Linux): ubuntu:GNOME

Graphics card: NVIDIA GeForce RTX 2060 - Driver Version: 530.30.02  - CUDA Version: 12.1 

Output of `docker info`: Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 5
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-46-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.48GiB
 Name: ---
 ID: 56YY:IM2S:JNRU:HPEH:A2F2:WL3Q:EIZG:DHGC:G2MY:WWL4:3KXW:ZKMW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

output log:
```
IMAGE=panard/mtgo:latest
run(): docker info
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 5
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-46-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.48GiB
 Name: FINANZA-ADMN
 ID: 56YY:IM2S:JNRU:HPEH:A2F2:WL3Q:EIZG:DHGC:G2MY:WWL4:3KXW:ZKMW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

run(): docker run --privileged --rm -e DISPLAY -v mtgo-data-matteo:/home/wine/.wine/host/ -v mtgo-data-matteo:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/matteo/.local/share/mtgo/Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/Europe/Rome --name mtgo_running -v /home/matteo/.local/share/mtgo/files:/home/wine/.wine/drive_c/users/wine/Documents --cpuset-cpus 0-3 panard/mtgo:latest mtgo
winetricks gdiplus=builtin sound=alsa winegstreamer=disabled wmp=disabled
Using winetricks 20230212-next - sha256sum: 0f7e30aee05ab6747ef0d6a089830b91f90a4f70534b6ec581e75ef1eb71fa68 with wine-8.10 and WINEARCH=win32
Using builtin override for following DLLs: gdiplus
Executing wine C:\windows\regedit.exe C:\windows\Temp\_builtin\override-dll.reg
Executing mkdir -p /home/wine/.wine/dosdevices/c:/windows/temp/_builtin
Executing w_do_call sound=alsa
Executing load_sound alsa
Setting sound driver to alsa
Executing wine C:\windows\regedit.exe C:\windows\Temp\set-sound.reg
Using  override for following DLLs: winegstreamer
Executing wine C:\windows\regedit.exe C:\windows\Temp\_disabled\override-dll.reg
Executing mkdir -p /home/wine/.wine/dosdevices/c:/windows/temp/_disabled
Using  override for following DLLs: wmp
Executing wine C:\windows\regedit.exe C:\windows\Temp\_disabled\override-dll.reg
Executing mkdir -p /home/wine/.wine/dosdevices/c:/windows/temp/_disabled
wineboot
0190:err:wineboot:ProcessStartupItems Couldn't get desktop folder.
wine /opt/mtgo/mtgo.exe
01a0:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
01a0:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
01a0:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0198:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0198:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0198:err:ole:com_get_class_object no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
021c:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
```
Downlaod log:
```
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3761.0 built by: NET48REL1
	clr.dll 			: 4.8.3761.0 built by: NET48REL1
	dfdll.dll 			: 4.8.3761.0 built by: NET48REL1
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/MTGO.application
						Server		: AkamaiNetStorage
	Deployment Provider url		: http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/MTGO.application
	Application url			: http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/3.4.133.4374.20230712093444/MTGO.exe.manifest
						Server		: AkamaiNetStorage

IDENTITIES
	Deployment Identity		: MTGO.application, Version=3.4.133.4374, Culture=neutral, PublicKeyToken=80b7d5223ec4322a, processorArchitecture=msil
	Application Identity		: MTGO.exe, Version=3.4.133.4374, Culture=neutral, PublicKeyToken=80b7d5223ec4322a, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/MTGO.application resulted in exception. Following failure messages were detected:
		+ Downloading http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/3.4.133.4374.20230712093444/CardDataSource/client_C06_DO.xml did not succeed.
		+ The remote server returned an error: (502) Bad Gateway.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [7/21/2023 10:20:19 AM] : Activation of http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/MTGO.application has started.
	* [7/21/2023 10:20:19 AM] : Processing of deployment manifest has successfully completed.
	* [7/21/2023 10:20:19 AM] : Installation of the application has started.
	* [7/21/2023 10:20:20 AM] : Processing of application manifest has successfully completed.
	* [7/21/2023 10:20:30 AM] : Found compatible runtime version 4.0.30319.
	* [7/21/2023 10:20:30 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [7/21/2023 10:20:35 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://mtgo.patch.daybreakgames.com/patch/mtg/live/client/3.4.133.4374.20230712093444/CardDataSource/client_C06_DO.xml did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (502) Bad Gateway.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

[output log](https://pastebin.com/AcFyDFnW)

**Comment by chumpblocckami** [comment]
After further inspection, i found out that this error was caused by my wifii and system configuration.
