### ISSUE TITLE
Support for user id other than 1000 (was: Running on linux with i3 desktop manager)

### ISSUE THREAD

**Issue by mitermayer** [pauleve/docker-mtgo#42]
Getting the following error when running on Linux and using the "i3" as desktop manager using the command `./run-mtgo`

```
0047:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0047:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0044:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0044:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0047:err:eventlog:ReportEventW L"Application: dfsvc.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.ComponentModel.Win32Exception\n   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)\n   at System.Windows.Forms.Cont"...

Unhandled Exception: System.ComponentModel.Win32Exception: Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Deployment.Application.UserInterfaceForm.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at System.Deployment.Application.SplashPiece.ShowSplash(Form parentForm)
   at System.Deployment.Application.SplashPiece..ctor(UserInterfaceForm parentForm, SplashInfo info)
   at System.Deployment.Application.UserInterfaceForm.InitializeContent()
   at System.Deployment.Application.UserInterfaceForm..ctor(ManualResetEvent readyEvent, SplashInfo splashInfo)
   at System.Deployment.Application.UserInterface.UIThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 47 at address 0x7b43c44c (thread 0047), starting debugger...
004a:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
004a:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

Am I missing any other setup steps ?

**Comment by pauleve** [comment]
Looks like a permission issue with X server.
Can you try doing `xhost +` before running `run-mtgo`?

**Comment by mitermayer** [comment]
I endup working around this issue by using `Xephyr` and attaching mtgo to the created fake 'X' server `:1`

Starting Xephyr

```
 Xephyr :1 -ac -br -screen 1024x768 -resizeable -reset -terminate
```

Attaching to it:

```
 run-mtgo -e DISPLAY=:1
```

**Comment by pauleve** [comment]
Ah, is your system using wayland instead of X? 
(`loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type`)

**Comment by mitermayer** [comment]
It says:

```
Type=x11
```

**Comment by mitermayer** [comment]
@pauleve i did not have a `.Xauthority` file at first, but then I created one to test with it and it made no difference

**Comment by pauleve** [comment]
Ok, interesting.. I thought xauth was now rather standard..
Can you try the command `xauth nlist $DISPLAY` and tell if there is at least one line showing up? (do not paste the content here). If yes, I'll try implementing the method from http://wiki.ros.org/docker/Tutorials/GUI 
Also, is your uid (`id -u`) 1000?

**Comment by mitermayer** [comment]
> Can you try the command xauth list $DISPLAY and tell if there is at least one line showing up? (do not paste the content here)

Yes there is one entry in there

> Also, is your uid (id -u) 1000?

My uid is 1001

**Comment by pauleve** [comment]
Can you try with the new version of the script?

**Comment by pauleve** [comment]
(note you may have to do `xhost +` beforehand)

**Comment by pauleve** [comment]
Anyway the current method assumes the uid is 1000, therefore it may not work properly, especially the persistent installation of mtgo.. I'll add it to my to-do list and keep you posted.

**Comment by mitermayer** [comment]
Hi @pauleve,

When chaning id from `1000` to `1001` and using the `xhost +` fixed the issue

**Comment by pauleve** [comment]
With the latest script, and doing `./run-mtgo --update` it should work and be persistent for any user now.
