### ISSUE TITLE
Errors on mtgo.exe open

### ISSUE THREAD

**Issue by joshuarichard** [pauleve/docker-mtgo#52]
Hey @pauleve, first of all - cool container!

I'm seeing an issue where when wine tries to open the execution file I get a few errors. Could you help me out with understanding these? Thanks!

```
wine /opt/mtgo/mtgo.exe
0037:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
2018/10/22 11:32:51 socat[18790] E connect(5, LEN=2 AF=1 "<anon>", 2): Invalid argument
0037:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0037:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

**Comment by joshuarichard** [comment]
Hey, quick update - so I uninstalled and reinstalled xquartz (I had two versions) and tried it again. This time, along with the same error message above, I got an xterm window that popped up with a bash shell. When I ls'ed I found myself in my home drive on my mac.

**Comment by joshuarichard** [comment]
Here's the full error from beginning to end.

```
$ ./run-mtgo 
Using network interface 'en0'
open -a XQuartz
socat on 192.168.1.16 forwarding to 
docker run --privileged --rm -e DISPLAY -v mtgo-data-josh:/home/wine/.wine/host/ -v mtgo-data-josh:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/New_York --name mtgo_running panard/mtgo:latest mtgo
winetricks sound=disabled winegstreamer=disabled
2018/10/22 11:53:42 socat[22782] E connect(5, LEN=2 AF=1 "<anon>", 2): Invalid argument
Using winetricks 20180815 - sha256sum: 9343f9174146c0fa4d34e18e05269ae772a45ba78e3d8786829fa21895f6f7f4 with wine-3.17 and WINEARCH=win32
Executing w_do_call sound=disabled
Executing load_sound disabled
Setting sound driver to disabled
Executing wine regedit C:windowsTemp_sound=disabledset-sound.reg
Using override for following DLLs: winegstreamer
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
wineboot
wine /opt/mtgo/mtgo.exe
003d:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
003d:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003d:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
003d:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
003d:err:ole:CoGetClassObject no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003d:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003d:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0051:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0051:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
004e:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
004e:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0051:err:eventlog:ReportEventW L"Application: dfsvc.exenFramework Version: v4.0.30319nDescription: The process was terminated due to an unhandled exception.nException Info: System.ComponentModel.Win32Exceptionn at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)n at System.Windows.Forms.Cont"...

Unhandled Exception: System.ComponentModel.Win32Exception: Error creating window handle.
at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
at System.Windows.Forms.Control.CreateHandle()
at System.Windows.Forms.Form.CreateHandle()
at System.Windows.Forms.Control.get_Handle()
at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
at System.Deployment.Application.UserInterfaceForm.SetVisibleCore(Boolean value)
at System.Windows.Forms.Control.set_Visible(Boolean value)
at System.Deployment.Application.SplashPiece.ShowSplash(Form parentForm)
at System.Deployment.Application.SplashPiece..ctor(UserInterfaceForm parentForm, SplashInfo info)
at System.Deployment.Application.UserInterfaceForm.InitializeContent()
at System.Deployment.Application.UserInterfaceForm..ctor(ManualResetEvent readyEvent, SplashInfo splashInfo)
at System.Deployment.Application.UserInterface.UIThread()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 51 at address 0x7b43c69c (thread 0051), starting debugger...
004e:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
004e:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0055:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0055:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Unhandled exception: 0xe0434352 in 32-bit code (0x7b43c69c).
Register dump:
CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
EIP:7b43c69c ESP:057bf3b4 EBP:057bf428 EFLAGS:00000216( - -- I -A-P- )
EAX:7b429825 EBX:00000010 ECX:057bf3d4 EDX:057bf494
ESI:00000000 EDI:00000001
Stack dump:
0x057bf3b4: 00124b78 23000000 00000000 e0434352
0x057bf3c4: 00000001 00000000 7b43c69c 00000005
0x057bf3d4: 80004005 00000000 00000000 00000000
0x057bf3e4: 00630000 00000000 01216018 00000005
0x057bf3f4: 00000000 00000000 00168e58 057bf4e8
0x057bf404: 00000001 006625ef 03571330 00662b38
Backtrace:
=>0 0x7b43c69c in kernel32 (+0x1c69c) (0x057bf428)
1 0x007e352f in clr (+0x1b352e) (0x057bf4c8)
2 0x007e3738 in clr (+0x1b3737) (0x057bf590)
3 0x0409c18c in system.windows.forms.ni (+0x1ac18b) (0x057bf608)
4 0x0409bddb in system.windows.forms.ni (+0x1abdda) (0x057bf664)
5 0x040a5b9c in system.windows.forms.ni (+0x1b5b9b) (0x057bf6b8)
6 0x0409dc3c in system.windows.forms.ni (+0x1adc3b) (0x057bf6c8)
7 0x0409adf5 in system.windows.forms.ni (+0x1aadf4) (0x057bf768)
8 0x040a59bc in system.windows.forms.ni (+0x1b59bb) (0x057bf790)
9 0x003c9fdb (0x057bf798)
10 0x04098f26 in system.windows.forms.ni (+0x1a8f25) (0x057bf7a0)
11 0x003c9f5e (0x057bf7ac)
12 0x003c8e78 (0x057bf7c0)
13 0x003c8668 (0x057bf7d4)
14 0x003c5106 (0x057bf7e4)
15 0x003c3c9f (0x057bf810)
16 0x79b052dd in mscorlib.ni (+0x3e52dc) (0x057bf81c)
17 0x79b4c512 in mscorlib.ni (+0x42c511) (0x057bf880)
18 0x79b4c446 in mscorlib.ni (+0x42c445) (0x057bf894)
19 0x79b4c401 in mscorlib.ni (+0x42c400) (0x057bf8b0)
20 0x79b05238 in mscorlib.ni (+0x3e5237) (0x057bf8c8)
21 0x0063ea96 in clr (+0xea95) (0x057bf8d4)
22 0x0065944f in clr (+0x2944e) (0x057bf928)
23 0x006596d3 in clr (+0x296d2) (0x057bf998)
24 0x0079ed4d in clr (+0x16ed4c) (0x057bfb0c)
25 0x0065b263 in clr (+0x2b262) (0x057bfb24)
26 0x0065b2cd in clr (+0x2b2cc) (0x057bfbc8)
27 0x0065b39a in clr (+0x2b399) (0x057bfc24)
28 0x0065b410 in clr (+0x2b40f) (0x057bfc48)
29 0x0079ec02 in clr (+0x16ec01) (0x057bfcc4)
30 0x00734971 in clr (+0x104970) (0x057bfedc)
31 0x7bc7d554 call_thread_func_wrapper+0xb() in ntdll (0x057bfeec)
32 0x7bc80937 in ntdll (+0x70936) (0x057bffdc)
33 0x7bc7d546 call_thread_exit_func+0x31() in ntdll (0x057bffec)
0x7b43c69c: addl $12,%esp
Modules:
Module Address Debug info Name (117 modules)
PE 400000- 408000 Deferred dfsvc
PE 630000- d11000 Export clr
PE d20000- e15000 Deferred msvcr120_clr0400
PE 3300000- 3380000 Deferred clrjit
PE 3380000- 3393000 Deferred nlssorting
PE 33a0000- 33c8000 Deferred dfdll
PE 3520000- 3eec000 Deferred system.ni
PE 3ef0000- 4b57000 Export system.windows.forms.ni
PE 5d90000- 5e78000 Deferred diasymreader
PE 10000000-1007d000 Deferred mscoreei
PE 60370000-60461000 Deferred system.configuration.ni
PE 60510000-60626000 Deferred dfshim
PE 61a00000-62121000 Deferred system.core.ni
PE 62160000-6287e000 Deferred system.xml.ni
PE 79000000-7904a000 Deferred mscoree
PE 79720000-7a9c2000 Export mscorlib.ni
PE 7aea0000-7b02f000 Deferred system.drawing.ni
ELF 7b400000-7b7eb000 Dwarf kernel32<elf>
-PE 7b420000-7b7eb000 kernel32
ELF 7bc00000-7bcfb000 Dwarf ntdll<elf>
-PE 7bc10000-7bcfb000 ntdll
ELF 7c000000-7c004000 Deferred <wine-loader>
ELF 7ef71000-7ef84000 Deferred libnss_files.so.2
ELF 7ef84000-7ef91000 Deferred libnss_nis.so.2
ELF 7ef91000-7efab000 Deferred libnsl.so.1
ELF 7efab000-7f000000 Deferred libm.so.6
ELF f51f7000-f5221000 Deferred iphlpapi<elf>
-PE f5200000-f5221000 iphlpapi
ELF f5221000-f5239000 Deferred libresolv.so.2
ELF f5239000-f5257000 Deferred jsproxy<elf>
-PE f5240000-f5257000 jsproxy
ELF f5257000-f5294000 Deferred winhttp<elf>
-PE f5260000-f5294000 winhttp
ELF f5294000-f52b0000 Deferred rasapi32<elf>
-PE f52a0000-f52b0000 rasapi32
ELF f52b0000-f52d8000 Deferred propsys<elf>
-PE f52c0000-f52d8000 propsys
ELF f52d8000-f5397000 Deferred windowscodecs<elf>
-PE f52f0000-f5397000 windowscodecs
ELF f5397000-f53ab000 Deferred psapi<elf>
-PE f53a0000-f53ab000 psapi
ELF f53ab000-f543c000 Deferred gdiplus<elf>
-PE f53c0000-f543c000 gdiplus
ELF f543c000-f5445000 Deferred libffi.so.6
ELF f5445000-f54d3000 Deferred libgmp.so.10
ELF f54d3000-f5509000 Deferred libhogweed.so.4
ELF f5509000-f5546000 Deferred libnettle.so.6
ELF f5546000-f557a000 Deferred libidn.so.11
ELF f557a000-f55dc000 Deferred libp11-kit.so.0
ELF f55dc000-f57a1000 Deferred libgnutls.so.30
ELF f57a1000-f586f000 Deferred crypt32<elf>
-PE f57b0000-f586f000 crypt32
ELF f586f000-f5890000 Deferred bcrypt<elf>
-PE f5870000-f5890000 bcrypt
ELF f5890000-f58cf000 Deferred rsaenh<elf>
-PE f58a0000-f58cf000 rsaenh
ELF f58cf000-f5909000 Deferred ws2_32<elf>
-PE f58e0000-f5909000 ws2_32
ELF f5909000-f5931000 Deferred mpr<elf>
-PE f5910000-f5931000 mpr
ELF f5931000-f59ac000 Deferred wininet<elf>
-PE f5940000-f59ac000 wininet
ELF f59ac000-f5a49000 Deferred urlmon<elf>
-PE f59c0000-f5a49000 urlmon
ELF f5a49000-f6404000 Deferred shell32<elf>
-PE f5a60000-f6404000 shell32
ELF f6404000-f644a000 Deferred usp10<elf>
-PE f6410000-f644a000 usp10
ELF f644a000-f6583000 Deferred comctl32<elf>
-PE f6450000-f6583000 comctl32
ELF f6583000-f65ba000 Deferred uxtheme<elf>
-PE f6590000-f65ba000 uxtheme
ELF f6901000-f6908000 Deferred libnss_dns.so.2
ELF f6908000-f691d000 Deferred libtasn1.so.6
ELF f691d000-f693b000 Deferred libgcc_s.so.1
ELF f6940000-f6a7c000 Deferred actxprxy<elf>
-PE f6960000-f6a7c000 actxprxy
ELF f6a7c000-f6bac000 Deferred oleaut32<elf>
-PE f6a90000-f6bac000 oleaut32
ELF f6bac000-f6bd2000 Deferred combase<elf>
-PE f6bb0000-f6bd2000 combase
ELF f6bd2000-f6be6000 Deferred api-ms-win-core-winrt-l1-1-0<elf>
-PE f6be0000-f6be6000 api-ms-win-core-winrt-l1-1-0
ELF f6be6000-f6c66000 Deferred rpcrt4<elf>
-PE f6bf0000-f6c66000 rpcrt4
ELF f6c66000-f6dbd000 Deferred ole32<elf>
-PE f6c80000-f6dbd000 ole32
ELF f6dbd000-f6de8000 Deferred kernelbase<elf>
-PE f6dc0000-f6de8000 kernelbase
ELF f6de8000-f6dfc000 Deferred api-ms-win-core-quirks-l1-1-0<elf>
-PE f6df0000-f6dfc000 api-ms-win-core-quirks-l1-1-0
ELF f6dfc000-f6e11000 Deferred api-ms-win-appmodel-runtime-l1-1-2<elf>
-PE f6e00000-f6e11000 api-ms-win-appmodel-runtime-l1-1-2
ELF f6e11000-f6e35000 Deferred imm32<elf>
-PE f6e20000-f6e35000 imm32
ELF f6e35000-f6e5f000 Deferred libexpat.so.1
ELF f6e5f000-f6ea2000 Deferred libfontconfig.so.1
ELF f6ea2000-f6edc000 Deferred libpng16.so.16
ELF f6edc000-f6ef7000 Deferred libz.so.1
ELF f6ef7000-f6fab000 Deferred libfreetype.so.6
ELF f6fab000-f6fc5000 Deferred version<elf>
-PE f6fb0000-f6fc5000 version
ELF f6fc5000-f70f1000 Deferred gdi32<elf>
-PE f6fd0000-f70f1000 gdi32
ELF f70f1000-f72f6000 Deferred user32<elf>
-PE f7100000-f72f6000 user32
ELF f72f6000-f736c000 Deferred shlwapi<elf>
-PE f7300000-f736c000 shlwapi
ELF f736c000-f73e5000 Deferred advapi32<elf>
-PE f7380000-f73e5000 advapi32
ELF f73e5000-f73ef000 Deferred libnss_compat.so.2
ELF f73f1000-f73f6000 Deferred libdl.so.2
ELF f73f6000-f75ad000 Deferred libc.so.6
ELF f75ad000-f75ca000 Deferred libpthread.so.0
ELF f75cf000-f7786000 Dwarf libwine.so.1
ELF f7789000-f77ae000 Deferred ld-linux.so.2
ELF f77b0000-f77b1000 Deferred [vdso].so
Threads:
process tid prio (all id:s are in hex)
0000000e services.exe
0000002e 0
0000002b 0
00000026 0
00000022 0
0000001f 0
00000015 0
00000014 0
00000013 0
00000010 0
0000000f 0
00000011 mscorsvw.exe
0000001a 0
00000019 0
00000016 0
00000012 0
00000017 explorer.exe
0000001e 0
0000001d 0
00000018 0
0000001b winedevice.exe
00000021 0
00000020 0
0000001c 0
00000024 plugplay.exe
00000028 0
00000027 0
00000025 0
00000029 winedevice.exe
0000002f 0
0000002d 0
0000002c 0
0000002a 0
00000041 (D) C:windowsMicrosoft.NETFrameworkv4.0.30319dfsvc.exe
00000053 0
00000052 0
00000051 0 <==
00000050 0
0000004f 0
0000004e 0
0000004a 0
00000049 0
00000047 0
00000046 0
00000045 0
00000044 2
00000043 0
00000042 0
System information:
Wine build: wine-3.17
Platform: i386
Version: Windows 7
Host system: Linux
Host version: 4.9.93-linuxkit-aufs
```

**Comment by joshuarichard** [comment]
I followed the tips in #17, got it all running with display issues like the open issue states. Going to try building on my machine directly, although I'd love to use the image.
