### ISSUE TITLE
crash when run run-mtgo

### ISSUE THREAD

**Issue by ChoKyuWon** [pauleve/docker-mtgo#53]
I use docker 18.06-ce in OSX.
when I run run-mtgo, this script is crashing with this err log.
```
Using network interface 'en0'
open -a XQuartz
socat on 192.168.0.46 forwarding to 
docker run --privileged --rm -e DISPLAY -v mtgo-data-kimdongjae:/home/wine/.wine/host/ -v mtgo-data-kimdongjae:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/Asia/Seoul --name mtgo_running panard/mtgo:latest mtgo
winetricks sound=disabled winegstreamer=disabled
Using winetricks 20180815 - sha256sum: 9343f9174146c0fa4d34e18e05269ae772a45ba78e3d8786829fa21895f6f7f4 with wine-3.17 and WINEARCH=win32
Executing w_do_call sound=disabled
Executing load_sound disabled
Setting sound driver to disabled
Executing wine regedit C:windowsTemp_sound=disabledset-sound.reg
Using override for following DLLs: winegstreamer
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
wineboot
wine /opt/mtgo/mtgo.exe
003c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
003c:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
003c:err:ole:CoGetClassObject no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
003c:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
003c:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:eventlog:ReportEventW L"Application: dfsvc.exenFramework Version: v4.0.30319nDescription: The process was terminated due to an unhandled exception.nException Info: System.ComponentModel.Win32Exceptionn at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)n at System.Windows.Forms.Cont"...

Unhandled Exception: 004d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
004d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
System.ComponentModel.Win32Exception: Error creating window handle.
at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
at System.Windows.Forms.Control.CreateHandle()
at System.Windows.Forms.Form.CreateHandle()
at System.Windows.Forms.Control.get_Handle()
at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
at System.Deployment.Application.UserInterfaceForm.SetVisibleCore(Boolean value)
at System.Windows.Forms.Control.set_Visible(Boolean value)
at System.Deployment.Application.SplashPiece.ShowSplash(Form parentForm)
at System.Deployment.Application.SplashPiece..ctor(UserInterfaceForm parentForm, SplashInfo info)
at System.Deployment.Application.UserInterfaceForm.InitializeContent()
at System.Deployment.Application.UserInterfaceForm..ctor(ManualResetEvent readyEvent, SplashInfo splashInfo)
at System.Deployment.Application.UserInterface.UIThread()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 50 at address 0x7b43c69c (thread 0050), starting debugger...
004d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
004d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0053:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0053:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Unhandled exception: 0xe0434352 in 32-bit code (0x7b43c69c).
Register dump:
CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
EIP:7b43c69c ESP:057bf3b4 EBP:057bf428 EFLAGS:00000216( - -- I -A-P- )
EAX:7b429825 EBX:00000010 ECX:057bf3d4 EDX:057bf494
ESI:00000000 EDI:00000001
Stack dump:
0x057bf3b4: 57a14d25 03521000 00150af0 e0434352
0x057bf3c4: 00000001 00000000 7b43c69c 00000005
0x057bf3d4: 80004005 00000000 00000000 00000000
0x057bf3e4: 00630000 00000000 011fe018 00000005
0x057bf3f4: 00000000 00000000 001678f0 057bf4e8
0x057bf404: 00000001 057bf428 7b466a3f ffffffff
Backtrace:
=>0 0x7b43c69c in kernel32 (+0x1c69c) (0x057bf428)
1 0x007e352f in clr (+0x1b352e) (0x057bf4c8)
2 0x007e3738 in clr (+0x1b3737) (0x057bf590)
3 0x0409c18c in system.windows.forms.ni (+0x1ac18b) (0x057bf608)
4 0x0409bddb in system.windows.forms.ni (+0x1abdda) (0x057bf664)
5 0x040a5b9c in system.windows.forms.ni (+0x1b5b9b) (0x057bf6b8)
6 0x0409dc3c in system.windows.forms.ni (+0x1adc3b) (0x057bf6c8)
7 0x0409adf5 in system.windows.forms.ni (+0x1aadf4) (0x057bf768)
8 0x040a59bc in system.windows.forms.ni (+0x1b59bb) (0x057bf790)
9 0x003c91d3 (0x057bf798)
10 0x04098f26 in system.windows.forms.ni (+0x1a8f25) (0x057bf7a0)
11 0x003c9156 (0x057bf7ac)
12 0x003c76a0 (0x057bf7c0)
13 0x003c74b8 (0x057bf7d4)
14 0x003c40e6 (0x057bf7e4)
15 0x003c3c37 (0x057bf810)
16 0x79b052dd in mscorlib.ni (+0x3e52dc) (0x057bf81c)
17 0x79b4c512 in mscorlib.ni (+0x42c511) (0x057bf880)
18 0x79b4c446 in mscorlib.ni (+0x42c445) (0x057bf894)
19 0x79b4c401 in mscorlib.ni (+0x42c400) (0x057bf8b0)
20 0x79b05238 in mscorlib.ni (+0x3e5237) (0x057bf8c8)
21 0x0063ea96 in clr (+0xea95) (0x057bf8d4)
22 0x0065944f in clr (+0x2944e) (0x057bf928)
23 0x006596d3 in clr (+0x296d2) (0x057bf998)
24 0x0079ed4d in clr (+0x16ed4c) (0x057bfb0c)
25 0x0065b263 in clr (+0x2b262) (0x057bfb24)
26 0x0065b2cd in clr (+0x2b2cc) (0x057bfbc8)
27 0x0065b39a in clr (+0x2b399) (0x057bfc24)
28 0x0065b410 in clr (+0x2b40f) (0x057bfc48)
29 0x0079ec02 in clr (+0x16ec01) (0x057bfcc4)
30 0x00734971 in clr (+0x104970) (0x057bfedc)
31 0x7bc7d554 call_thread_func_wrapper+0xb() in ntdll (0x057bfeec)
32 0x7bc80937 in ntdll (+0x70936) (0x057bffdc)
33 0x7bc7d546 call_thread_exit_func+0x31() in ntdll (0x057bffec)
0x7b43c69c: addl $12,%esp
Modules:
Module Address Debug info Name (117 modules)
PE 400000- 408000 Deferred dfsvc
PE 630000- d11000 Export clr
PE d20000- e15000 Deferred msvcr120_clr0400
PE 3300000- 3380000 Deferred clrjit
PE 3380000- 3393000 Deferred nlssorting
PE 33a0000- 33c8000 Deferred dfdll
PE 3520000- 3eec000 Deferred system.ni
PE 3ef0000- 4b57000 Export system.windows.forms.ni
PE 5c90000- 5d78000 Deferred diasymreader
PE 10000000-1007d000 Deferred mscoreei
PE 60370000-60461000 Deferred system.configuration.ni
PE 60510000-60626000 Deferred dfshim
PE 61a00000-62121000 Deferred system.core.ni
PE 62160000-6287e000 Deferred system.xml.ni
PE 79000000-7904a000 Deferred mscoree
PE 79720000-7a9c2000 Export mscorlib.ni
PE 7aea0000-7b02f000 Deferred system.drawing.ni
ELF 7b400000-7b7eb000 Dwarf kernel32<elf>
-PE 7b420000-7b7eb000 kernel32
ELF 7bc00000-7bcfb000 Dwarf ntdll<elf>
-PE 7bc10000-7bcfb000 ntdll
ELF 7c000000-7c004000 Deferred <wine-loader>
ELF 7ef67000-7ef7a000 Deferred libnss_files.so.2
ELF 7ef7a000-7ef87000 Deferred libnss_nis.so.2
ELF 7ef87000-7efa1000 Deferred libnsl.so.1
ELF 7efa1000-7efab000 Deferred libnss_compat.so.2
ELF 7efab000-7f000000 Deferred libm.so.6
ELF f5214000-f523e000 Deferred iphlpapi<elf>
-PE f5220000-f523e000 iphlpapi
ELF f523e000-f5256000 Deferred libresolv.so.2
ELF f5256000-f525d000 Deferred libnss_dns.so.2
ELF f525d000-f527b000 Deferred jsproxy<elf>
-PE f5260000-f527b000 jsproxy
ELF f527b000-f52b8000 Deferred winhttp<elf>
-PE f5280000-f52b8000 winhttp
ELF f52b8000-f52d4000 Deferred rasapi32<elf>
-PE f52c0000-f52d4000 rasapi32
ELF f52d4000-f52e8000 Deferred psapi<elf>
-PE f52e0000-f52e8000 psapi
ELF f52e8000-f5310000 Deferred propsys<elf>
-PE f52f0000-f5310000 propsys
ELF f5310000-f53cf000 Deferred windowscodecs<elf>
-PE f5320000-f53cf000 windowscodecs
ELF f53cf000-f53d8000 Deferred libffi.so.6
ELF f53d8000-f5466000 Deferred libgmp.so.10
ELF f5466000-f549c000 Deferred libhogweed.so.4
ELF f549c000-f54d9000 Deferred libnettle.so.6
ELF f54d9000-f550d000 Deferred libidn.so.11
ELF f550d000-f556f000 Deferred libp11-kit.so.0
ELF f556f000-f5734000 Deferred libgnutls.so.30
ELF f5734000-f5802000 Deferred crypt32<elf>
-PE f5740000-f5802000 crypt32
ELF f5802000-f5823000 Deferred bcrypt<elf>
-PE f5810000-f5823000 bcrypt
ELF f5823000-f5862000 Deferred rsaenh<elf>
-PE f5830000-f5862000 rsaenh
ELF f5862000-f58f3000 Deferred gdiplus<elf>
-PE f5870000-f58f3000 gdiplus
ELF f58f3000-f592d000 Deferred ws2_32<elf>
-PE f5900000-f592d000 ws2_32
ELF f592d000-f5955000 Deferred mpr<elf>
-PE f5930000-f5955000 mpr
ELF f5955000-f59d0000 Deferred wininet<elf>
-PE f5960000-f59d0000 wininet
ELF f59d0000-f5a6d000 Deferred urlmon<elf>
-PE f59e0000-f5a6d000 urlmon
ELF f5a6d000-f6428000 Deferred shell32<elf>
-PE f5a80000-f6428000 shell32
ELF f6428000-f646e000 Deferred usp10<elf>
-PE f6430000-f646e000 usp10
ELF f646e000-f65a7000 Deferred comctl32<elf>
-PE f6480000-f65a7000 comctl32
ELF f65a7000-f65de000 Deferred uxtheme<elf>
-PE f65b0000-f65de000 uxtheme
ELF f6906000-f691b000 Deferred libtasn1.so.6
ELF f693f000-f695d000 Deferred libgcc_s.so.1
ELF f6962000-f6a9e000 Deferred actxprxy<elf>
-PE f6980000-f6a9e000 actxprxy
ELF f6a9e000-f6bce000 Deferred oleaut32<elf>
-PE f6ab0000-f6bce000 oleaut32
ELF f6bce000-f6bf4000 Deferred combase<elf>
-PE f6bd0000-f6bf4000 combase
ELF f6bf4000-f6c08000 Deferred api-ms-win-core-winrt-l1-1-0<elf>
-PE f6c00000-f6c08000 api-ms-win-core-winrt-l1-1-0
ELF f6c08000-f6c88000 Deferred rpcrt4<elf>
-PE f6c10000-f6c88000 rpcrt4
ELF f6c88000-f6ddf000 Deferred ole32<elf>
-PE f6ca0000-f6ddf000 ole32
ELF f6ddf000-f6e0a000 Deferred kernelbase<elf>
-PE f6df0000-f6e0a000 kernelbase
ELF f6e0a000-f6e1e000 Deferred api-ms-win-core-quirks-l1-1-0<elf>
-PE f6e10000-f6e1e000 api-ms-win-core-quirks-l1-1-0
ELF f6e1e000-f6e33000 Deferred api-ms-win-appmodel-runtime-l1-1-2<elf>
-PE f6e20000-f6e33000 api-ms-win-appmodel-runtime-l1-1-2
ELF f6e33000-f6e57000 Deferred imm32<elf>
-PE f6e40000-f6e57000 imm32
ELF f6e57000-f6e81000 Deferred libexpat.so.1
ELF f6e81000-f6ec4000 Deferred libfontconfig.so.1
ELF f6ec4000-f6efe000 Deferred libpng16.so.16
ELF f6efe000-f6f19000 Deferred libz.so.1
ELF f6f19000-f6fcd000 Deferred libfreetype.so.6
ELF f6fcd000-f6fe7000 Deferred version<elf>
-PE f6fd0000-f6fe7000 version
ELF f6fe7000-f7113000 Deferred gdi32<elf>
-PE f6ff0000-f7113000 gdi32
ELF f7113000-f7318000 Deferred user32<elf>
-PE f7130000-f7318000 user32
ELF f7318000-f738e000 Deferred shlwapi<elf>
-PE f7330000-f738e000 shlwapi
ELF f738e000-f7407000 Deferred advapi32<elf>
-PE f73a0000-f7407000 advapi32
ELF f7409000-f740e000 Deferred libdl.so.2
ELF f740e000-f75c5000 Deferred libc.so.6
ELF f75c5000-f75e2000 Deferred libpthread.so.0
ELF f75e7000-f779e000 Dwarf libwine.so.1
ELF f77a1000-f77c6000 Deferred ld-linux.so.2
ELF f77c8000-f77c9000 Deferred [vdso].so
Threads:
process tid prio (all id:s are in hex)
0000000e services.exe
0000002d 0
0000002a 0
00000025 0
0000001f 0
00000017 0
00000016 0
00000015 0
00000010 0
0000000f 0
00000011 mscorsvw.exe
0000001c 0
0000001a 0
00000018 0
00000012 0
00000013 explorer.exe
0000001b 0
00000019 0
00000014 0
0000001d winedevice.exe
00000021 0
00000020 0
0000001e 0
00000023 plugplay.exe
00000027 0
00000026 0
00000024 0
00000028 winedevice.exe
0000002e 0
0000002c 0
0000002b 0
00000029 0
00000040 (D) C:windowsMicrosoft.NETFrameworkv4.0.30319dfsvc.exe
00000054 0
00000051 0
00000050 0 <==
0000004f 0
0000004e 0
0000004d 0
00000049 0
00000048 0
00000046 0
00000045 0
00000044 0
00000043 2
00000042 0
00000041 0
System information:
Wine build: wine-3.17
Platform: i386
Version: Windows 7
Host system: Linux
Host version: 4.9.93-linuxkit-aufs
```
what can i do?

**Comment by ChoKyuWon** [comment]
This error is not appear when I reboot system! I don't know why, but the error is solved

**Comment by ChoKyuWon** [comment]
This error is not appear when I reboot system! I don't know why, but the error is solved

**Comment by pauleve** [comment]
XQuartz requires to reboot your system after installation, the error message is related to that.
